FROM jenkins:latest
USER root
RUN apt-get -qqy update
RUN apt-get install -y python-pip
RUN apt-get install -y net-tools
RUN apt-get install -qqy openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile
#RUN nohup java -jar /usr/share/jenkins/jenkins.war &
EXPOSE 22

VOLUME ["/var/log/sshd"]
CMD ["/usr/sbin/sshd", "-D"]
