registry:
  image: registry:2
  restart: always
  ports:
        - 5000:5000
  volumes:
        - /home/mateuo/docker_registry/certs:/certs
        - /home/mateuo/docker_registry/registry_data:/var/lib/registry  
        - /home/mateuo/docker_registry/auth:/auth
  environment:
          REGISTRY_HTTP_TLS_CERTIFICATE: /certs/docker.crt
          REGISTRY_HTTP_TLS_KEY: /certs/docker.key
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
          NO_PROXY: 0
